### PR TITLE
Added requirements.txt with dependencies

### PR DESCRIPTION
**Pull request by ruth7873**
I created a virtual environment and there I install the basic neccesary dependency of the project.
in order to create the venv you have to:
1. Create a Virtual Environment (if not already created)
          python -m venv venv
2. Activate the Virtual Environment
         .\venv\Scripts\activate

and than you can install all the libraries from the requirements file:
         pip install -r requirements.txt

thanks!!

### CODE REVIEW

**Comment by ChayaCodes** [comment]
@ruth7873  Please also update this change in the documentation.

**Comment by ChayaCodes** [comment]
This pull request is related to #8

**Comment by ruth7873** [comment]
Im sorry...
I don't know how to change it

**Comment by ChayaCodes** [comment]
Just change the README.md file

**Pull request merged**
