### PR TITLE
create basic home page

### PR DESCRIPTION
**Pull request by estush**
there is to option here CSS ans SCSS
if you want to use SCSS you have to install it

### CODE REVIEW

**Comment by estush** [comment]
#31

**Comment by ChayaCodes** [comment]
Great @estush,
I think we'll want to keep the app active after Hanukkah, but for now it's fine

**Comment by ChayaCodes** [comment]
Is the homepage complete?

**Comment by estush** [comment]
like i show you

‫בתאריך יום ג׳, 17 בדצמ׳ 2024 ב-19:18 מאת ‪chaya kremer‬‏ <‪
***@***.***‬‏>:‬

**Pull request merged**
