### PR TITLE
Added Responsive Navigation Bar with MUI issue #29

### PR DESCRIPTION
**Pull request by rivka14**
Implemented a responsive navigation bar using MUI with the following links: דף הבית, התחברות, חידונים, צור חידון. 
The navigation adapts to both mobile and desktop views, with a hamburger menu for smaller screens.

### CODE REVIEW

**Comment by ChayaCodes** [comment]
@rivka14, this pull request has a merge conflicts, so I cant merge it. please do git pull and resolve the conflicts, and then update this pull request.

**Comment by rivka14** [comment]
@ChayaCodes I think I fixed it, please check if it's ok.

**Comment by ChayaCodes** [comment]
no, it's still have conflicts.
you can see the warning

**Comment by ChayaCodes** [comment]
it's still have conflicts.

**Pull request merged**
